services:

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      args:
        - UID=1000
        - GID=1000
    volumes:
      - ./server:/home/user/server
    network_mode: host
    working_dir: /home/user/server
    entrypoint: /bin/bash

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
      args:
        - UID=1000
        - GID=1000
    volumes:
      - ./ui:/home/user/ui
    working_dir: /home/user/ui
    entrypoint: /bin/bash
