services:

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
      args:
        - UID=1000
        - GID=1000
    networks:
      - app
    volumes:
      - ./server:/home/user/server
    working_dir: /home/user/server
    entrypoint: /bin/bash

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
      args:
        - UID=1000
        - GID=1000
    networks:
      - app
    ports:
      - 3000:3000
    volumes:
      - ./ui:/home/user/ui
    working_dir: /home/user/ui
    entrypoint: /bin/bash

  db:
    image: postgres:latest 
    networks:
      - app
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:

networks:
  app:
